import "./AdminLogin.test.js"
import "./CreateUser.test.js"
import "./Deposit.test.js"
import "./Withdraw.test.js"
import "./Sendmoney.test.js"
import "./Payment.test.js"
import "./CheckBalance.test.js"